# Generated by Django 4.1.7 on 2023-02-17 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('body', models.TextField(max_length=5000, verbose_name='Основной текст')),
                ('images', models.ImageField(blank=True, upload_to='img/')),
                ('article_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Developments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('body', models.TextField(max_length=5000, verbose_name='Основной текст')),
                ('images', models.ImageField(blank=True, upload_to='static/img')),
                ('develop_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=15, verbose_name='Имя')),
                ('middlename', models.CharField(max_length=15, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Адрес электронной почты')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Номер телефона')),
                ('body', models.TextField(verbose_name='Ваш отзыв')),
                ('feedback_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации отзыва')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('body', models.TextField(max_length=5000, verbose_name='Основной текст')),
                ('images', models.ImageField(null=True, upload_to='static/img')),
                ('portfolio_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
        ),
    ]
