# Generated by Django 4.1.7 on 2023-02-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_comment_is_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='is_pub',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
