# Generated by Django 4.1.7 on 2023-03-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_feedbacks_is_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, help_text='Не обязательное поле', max_length=254, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='phone',
            field=models.CharField(blank=True, help_text='Не обязательное поле', max_length=10, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='email',
            field=models.EmailField(blank=True, help_text='Не обязательное поле', max_length=254, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='phone',
            field=models.CharField(blank=True, help_text='Не обязательное поле', max_length=10, verbose_name='Номер телефона'),
        ),
    ]
