# Generated by Django 4.1.7 on 2023-03-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_comment_email_alter_comment_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developments',
            name='body',
            field=models.TextField(max_length=6000, verbose_name='Основной текст'),
        ),
    ]
