# Generated by Django 4.1.7 on 2023-03-14 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_developments_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='images',
        ),
        migrations.RemoveField(
            model_name='developments',
            name='images',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='images',
        ),
    ]
