# Generated by Django 4.1.7 on 2023-03-14 07:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_articles_images_remove_developments_images_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentArticle',
        ),
        migrations.CreateModel(
            name='CommentDevelop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=15, verbose_name='Имя')),
                ('middlename', models.CharField(max_length=15, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, help_text='Не обязательное поле', max_length=254, verbose_name='Адрес электронной почты')),
                ('phone', models.CharField(blank=True, help_text='Не обязательное поле', max_length=10, verbose_name='Номер телефона')),
                ('body', models.TextField(verbose_name='Ваш комментарий')),
                ('feedback_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки отзыва')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации отзыва')),
                ('is_pub', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('develop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.articles')),
            ],
        ),
    ]
