# Generated by Django 4.1.7 on 2023-03-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_page_section_alter_commentdevelop_develop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
