# Generated by Django 4.1.7 on 2023-03-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='Developments',
            new_name='Development',
        ),
        migrations.RenameModel(
            old_name='Feedbacks',
            new_name='Feedback',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='section_id',
            new_name='section',
        ),
    ]
