# Generated by Django 4.1.7 on 2023-03-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_articles_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='development',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Заголовок'),
        ),
    ]
