# Generated by Django 4.1.7 on 2023-08-26 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_page_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.section'),
        ),
    ]
