# Generated by Django 4.1.7 on 2023-09-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_page_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarticle',
            name='phone',
            field=models.CharField(blank=True, help_text='Не обязательное поле', max_length=16, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='commentdevelop',
            name='phone',
            field=models.CharField(blank=True, help_text='Не обязательное поле', max_length=16, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(blank=True, help_text='Не обязательное поле', max_length=16, verbose_name='Номер телефона'),
        ),
    ]
